package com.git.blog.dao.entity;

import java.util.Date;

public class UpdateRecordEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_record.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_record.record
     *
     * @mbg.generated
     */
    private String record;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_record.id
     *
     * @return the value of update_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_record.id
     *
     * @param id the value for update_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_record.table_name
     *
     * @return the value of update_record.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_record.table_name
     *
     * @param tableName the value for update_record.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_record.create_time
     *
     * @return the value of update_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_record.create_time
     *
     * @param createTime the value for update_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_record.record
     *
     * @return the value of update_record.record
     *
     * @mbg.generated
     */
    public String getRecord() {
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_record.record
     *
     * @param record the value for update_record.record
     *
     * @mbg.generated
     */
    public void setRecord(String record) {
        this.record = record == null ? null : record.trim();
    }
}