package com.git.blog.dao.mapper;

import com.git.blog.dao.entity.UpdateRecordEntity;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UpdateRecordEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_record
     *
     * @mbg.generated
     */
    @Delete({
        "delete from update_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_record
     *
     * @mbg.generated
     */
    @Insert({
        "insert into update_record (id, table_name, ",
        "create_time, record)",
        "values (#{id,jdbcType=BIGINT}, #{tableName,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{record,jdbcType=LONGVARCHAR})"
    })
    int insert(UpdateRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_record
     *
     * @mbg.generated
     */
    int insertSelective(UpdateRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_record
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, table_name, create_time, record",
        "from update_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.git.blog.dao.mapper.UpdateRecordEntityMapper.ResultMapWithBLOBs")
    UpdateRecordEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UpdateRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_record
     *
     * @mbg.generated
     */
    @Update({
        "update update_record",
        "set table_name = #{tableName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "record = #{record,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(UpdateRecordEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_record
     *
     * @mbg.generated
     */
    @Update({
        "update update_record",
        "set table_name = #{tableName,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UpdateRecordEntity record);
}