package com.git.blog.dao.mapper;

import com.git.blog.dao.entity.UserEntity;
import org.apache.ibatis.annotations.*;

import java.util.List;
import java.util.Map;

public interface UserEntityMapper {

    @Select("select * from user")
    List<UserEntity> selectAll();

    @Select("select count(*) from user where account=#{account}")
    boolean exists(String account);

    @Select("select count(*) from user")
    int countAllUsers();

    @Select("select count(*) from user where account=#{account} and enable=1")
    boolean accountEnable(String account);

    @Select("select count(*) from user where account=#{account} and password=#{password}")
    boolean login(@Param("account") String account, @Param("password") String password);

    //@Select("select * from user where account=#{account} and password=#{password}")
    @Select({
            "select",
            "id, account, password, enable, update_time, create_time",
            "from user",
            "where account=#{account} and password=#{password}"
    })
    UserEntity selectBy(@Param("account") String account, @Param("password") String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into user (id, account, ",
        "password, enable, update_time, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{account,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{enable,jdbcType=BIT}, #{updateTime,jdbcType=TIMESTAMP}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, account, password, enable, update_time, create_time",
        "from user",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.git.blog.dao.mapper.UserEntityMapper.BaseResultMap")
    UserEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Update({
        "update user",
        "set account = #{account,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "enable = #{enable,jdbcType=BIT},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserEntity record);

}